import type { GitignoreRuleSet } from '../types';

export const languageRules: Record<string, GitignoreRuleSet> = {
    javascript: {
        id: 'javascript',
        name: 'JavaScript / TypeScript',
        content: [
            'node_modules/',
            'npm-debug.log*',
            'yarn-debug.log*',
            'yarn-error.log*',
            'pnpm-debug.log*',
            '.npm/',
            'dist/',
            'build/',
            'coverage/',
            '.nyc_output/',
        ],
    },
    python: {
        id: 'python',
        name: 'Python',
        content: [
            '__pycache__/',
            '*.py[cod]',
            '*$py.class',
            '*.so',
            '.Python',
            'build/',
            'develop-eggs/',
            'dist/',
            'downloads/',
            'eggs/',
            '.eggs/',
            'lib/',
            'lib64/',
            'parts/',
            'sdist/',
            'var/',
            'wheels/',
            '*.egg-info/',
            '.installed.cfg',
            '*.egg',
            'MANIFEST',
            '.env',
            '.venv',
            'env/',
            'venv/',
            'ENV/',
            'env.bak/',
            'venv.bak/',
        ],
    },
    rust: {
        id: 'rust',
        name: 'Rust',
        content: [
            '/target/',
            '**/*.rs.bk',
            'Cargo.lock',
        ],
    },
    cpp: {
        id: 'cpp',
        name: 'C / C++',
        content: [
            '*.o',
            '*.obj',
            '*.so',
            '*.dll',
            '*.dylib',
            '*.exe',
            '*.lib',
            '*.out',
            '*.a',
            '*.sln',
            '*.vcxproj',
            '*.vcxproj.filters',
            '*.vcxproj.user',
            'build/',
        ],
    },
    go: {
        id: 'go',
        name: 'Go',
        content: [
            'bin/',
            'pkg/',
            '*.exe',
            '*.exe~',
            '*.dll',
            '*.so',
            '*.dylib',
            '*.test',
            '*.out',
            'vendor/',
        ],
    },
};
